#!/bin/bash

## an attemt to build the bio_db_repo(sitory) on the cluster
## run this with: sbatch build_bio_db_repo
## check queue with squeue
##
## this script builds bio_db_repo at ...fixme: 

## Resource Request
#SBATCH --job-name=build_bio_db_repo
## %j is job number, %x is the job name above
#SBATCH --output=/mnt/lustre/RDS-live/angelopoulos/aurochs/clust/outs/out-%x-%j.txt
## 12 hours
#SBATCH --time=1-12:00:00
#SBATCH --ntasks=1
## fixme: test against 1
#SBATCH --cpus-per-task=8
## why not :) :
#SBATCH --mem-per-cpu=128G

## Job Steps
echo "Starting: in sbatch we asked for 8 threads and 128G mem"
echo `date`
echo $PATH
## srun echo "echo LD_LIBRARY_PATH"
## srun echo $LD_LIBRARY_PATH
## srun echo "ls /cm/shared/apps/slurm/current/lib64/slurm"
## srun ls /cm/shared/apps/slurm/current/lib64/slurm
## srun echo "ls /cm/shared/apps/slurm/current/lib64"
## srun ls /cm/shared/apps/slurm/current/lib64
## cd /mnt/lustre/RDS-live/angelopoulos/local/src/swipl-devel
## LD_LIBRARY_PATH=/mnt/lustre/RDS-live/angelopoulos/local/lib/:$LD_LIBRARY_PATH
## srun echo "echo LD_LIBRARY_PATH"
## srun echo $LD_LIBRARY_PATH
cd /mnt/lustre/RDS-ephemeral/angelopoulos/local.home/src/packs/bio_db
git pull
cd auxil/build_repo/species

srun upsh std_repo

echo `date`
sleep 10
echo "The End"
# change urls to new central location
