#!/bin/bash

## customise to your own set-up 

OUTS_DIR=${HOME}/aurochs/clust/outs/
PACKS_DIR=/mnt/lustre/RDS-ephemeral/angelopoulos/local.home/src/packs/

## an attemt to build the bio_db_repo(sitory) on the cluster
## run this with: sbatch build_bio_db_repo
## check queue with squeue
##
## this script builds bio_db_repo at ...fixme: 

## Resource Request
#SBATCH --job-name=build_bio_db_repo_slurm
## %j is job number, %x is the job name above
#SBATCH --output=${OUTS_DIR}/out-%x-%j.txt
## 6 hours
#SBATCH --time=1-6:00:00
#SBATCH --ntasks=1
## fixme: test against 1
#SBATCH --cpus-per-task=8
## why not :) :
#SBATCH --mem-per-cpu=128G

## Job Steps
echo "Starting: in sbatch we asked for 8 threads and 128G mem"
echo `date`
echo $PATH
cd ${PACKS_DIR}/bio_db
git pull
cd auxil/build_repo/species

srun upsh std_repo

echo `date`
sleep 10
echo "The End"
# change urls to new central location
