%% bio_db_data_predicate( Pn, Pa, Org, Cell).
%
% Auto-generated predicate; listing and name-documenting all data predicates in bio_db.
% This predicate is statically generated from the source cell files.
%
%  * chicken/cgnc.pl
%    * cgnc_galg_cgnc_curs/2
%    * cgnc_galg_cgnc_edat/2
%    * cgnc_galg_cgnc_ncbi/2
%    * cgnc_galg_cgnc_ensg/2
%    * cgnc_galg_cgnc_name/2
%    * cgnc_galg_cgnc_symb/2
%    * cgnc_galg_cgnc_syno/2
%  * chicken/ense.pl
%    * ense_galg_enst_chrl/5
%    * ense_galg_ensg_chrl/5
%    * ense_galg_enst_ensg/2
%    * ense_galg_ensg_symb/2
%    * ense_gg6a_enst_chrl/5
%    * ense_gg6a_ensg_chrl/5
%    * ense_gg6a_enst_ensg/2
%    * ense_gg6a_ensg_symb/2
%  * chicken/gont.pl
%    * gont_galg_symb_gont/4
%  * chicken/reac.pl
%    * reac_galg_ncbi_reac/2
%    * reac_galg_ncbi_reap/2
%    * reac_galg_reac_reap/3
%    * reac_galg_reac_recl/2
%    * reac_galg_reac_recn/2
%    * reac_galg_reap_repn/2
%  * chicken/strg.pl
%    * strg_galg_edge_ensp/3
%    * strg_galg_edge_symb/3
%    * strg_galg_ensp_symb/2
%  * chicken/unip.pl
%    * unip_galg_unip_ensp/2
%    * unip_galg_unip_ncbi/2
%    * unip_galg_unip_gyno/2
%    * unip_galg_unip_strp/2
%    * unip_galg_unip_symb/2
%  * human/ense.pl
%    * ense_homs_ensg_hgnc/2
%    * ense_homs_ensg_symb/2
%    * ense_homs_enst_chrl/5
%    * ense_homs_ensg_chrl/5
%    * ense_homs_enst_ensg/2
%  * human/gont.pl
%    * gont_homs_edge_gisa/2
%    * gont_homs_edge_greg/2
%    * gont_homs_edge_gprg/2
%    * gont_homs_edge_gnrg/2
%    * gont_homs_edge_gpof/2
%    * gont_homs_gont_symb/3
%    * gont_homs_gont_gonm/2
%    * gont_homs_symb_gont/3
%  * human/hgnc.pl
%    * hgnc_homs_ccds_hgnc/2
%    * hgnc_homs_ensg_hgnc/2
%    * hgnc_homs_ncbi_hgnc/2
%    * hgnc_homs_ncbi_symb/2
%    * hgnc_homs_hgnc_ccds/2
%    * hgnc_homs_hgnc_chrb/2
%    * hgnc_homs_hgnc_ensg/2
%    * hgnc_homs_hgnc_ncbi/2
%    * hgnc_homs_hgnc_name/2
%    * hgnc_homs_hgnc_symb/2
%    * hgnc_homs_prev_symb/2
%    * hgnc_homs_symb_ncbi/2
%    * hgnc_homs_symb_hgnc/2
%    * hgnc_homs_syno_symb/2
%  * human/ncbi.pl
%    * ncbi_homs_ensg_ncbi/2
%    * ncbi_homs_ensp_ncbi/2
%    * ncbi_homs_ncbi_ensg/2
%    * ncbi_homs_ncbi_ensp/2
%    * ncbi_homs_rnuc_symb/2
%    * ncbi_homs_dnuc_symb/2
%  * human/pros.pl
%    * pros_homs_pros_prsn/2
%    * pros_homs_pros_sprt/7
%  * human/reac.pl
%    * reac_homs_ncbi_reac/2
%    * reac_homs_ncbi_reap/2
%    * reac_homs_reac_reap/3
%    * reac_homs_reac_recl/2
%    * reac_homs_reac_recn/2
%    * reac_homs_reap_repn/2
%  * human/strg.pl
%    * strg_homs_edge_ensp/3
%    * strg_homs_edge_symb/3
%  * human/unip.pl
%    * unip_homs_hgnc_unip/2
%    * unip_homs_ensp_unip/2
%    * unip_homs_trem_nucs/2
%    * unip_homs_unip_ncbi/2
%    * unip_homs_unip_hgnc/2
%    * unip_homs_sprt_seqn/2
%    * unip_homs_trem_seqn/2
%  * mouse/ense.pl
%    * ense_musm_ensg_mgim/2
%    * ense_musm_ensg_symb/2
%    * ense_musm_enst_chrl/5
%    * ense_musm_ensg_chrl/5
%    * ense_musm_enst_ensg/2
%  * mouse/gont.pl
%    * gont_musm_mgim_gont/4
%    * gont_musm_gont_symb/4
%  * mouse/mgim.pl
%    * mgim_musm_mgim_chrl/5
%    * mgim_musm_mgim_genb/2
%    * mgim_musm_mgim_mrks/2
%    * mgim_musm_mgim_ncbi/2
%    * mgim_musm_mgim_symb/2
%    * mgim_musm_mgim_unip/2
%    * mgim_musm_symb_wdra/2
%    * mgim_musm_mrks_mnme/2
%    * mgim_musm_msyn_mgim/2
%  * mouse/ncbi.pl
%    * ncbi_musm_nsyn_symb/2
%  * mouse/reac.pl
%    * reac_musm_ncbi_reac/2
%    * reac_musm_ncbi_reap/2
%    * reac_musm_reac_reap/3
%    * reac_musm_reac_recl/2
%    * reac_musm_reac_recn/2
%    * reac_musm_reap_repn/2
%  * mouse/strg.pl
%    * strg_musm_edge_ensp/3
%    * strg_musm_edge_symb/3
%  * mouse/unip.pl
%    * unip_musm_ensp_unip/2
%    * unip_musm_mgim_unip/2
%    * unip_musm_trem_nucs/2
%    * unip_musm_unip_ncbi/2
%    * unip_musm_unip_symb/2
%    * unip_musm_gyno_unip/2
